[build]
publish = "dist"
command = "yarn build"

[build.environment]
NODE_VERSION = "22"

[functions]
    directory = "api"

[[redirects]]
    from = '/score'
    to = '/.netlify/functions/score'
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = '/url'
    to = '/.netlify/functions/url'
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/.well-known/*"
    to = "/.well-known/:splat"
    status = 200

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
